// Constant request users.
export const FETCH_USERS = {
  PENDING: 'FETCH_PENDING',
  SUCCESS: 'FETCH_SUCCESS',
  FAILURE: 'FETCH_FAILURE',
};

export const UPDATE_USER = {
  PENDING: 'UPDATE_PENDING',
  SUCCESS: 'UPDATE_SUCCESS',
  FAILURE: 'UPDATE_FAILURE',
};

export const DELETE_USER = {
  PENDING: 'DELETE_PENDING',
  SUCCESS: 'DELETE_SUCCESS',
  FAILURE: 'DELETE_FAILURE',
};
