export const COUNTRIES = [
  { name: 'Ascension', code: 'ac' },
  { name: 'Andorra', code: 'ad' },
  { name: 'United Arab Emirates', code: 'ae' },
  { name: 'Afghanistan', code: 'af' },
  { name: 'Afar', code: 'afar' },
  { name: 'Antigua and Barbuda', code: 'ag' },
  { name: 'Anguilla', code: 'ai' },
  { name: 'Albania', code: 'al' },
  { name: 'Armenia', code: 'am' },
  { name: 'Angola', code: 'ao' },
  { name: 'Antarctica', code: 'aq' },
  { name: 'Argentina', code: 'ar' },
  { name: 'American Samoa', code: 'as' },
  { name: 'Austria', code: 'at' },
  { name: 'Australia', code: 'au' },
  { name: 'Aboriginal Australians', code: 'au-aboriginal' },
  { name: 'Australian Capital Territory', code: 'au-act' },
  { name: 'Australian Northern Territory', code: 'au-nt' },
  { name: 'Queensland', code: 'au-qld' },
  { name: 'Tasmania', code: 'au-tas' },
  { name: 'Victoria', code: 'au-vic' },
  { name: 'Western Australia', code: 'au-wa' },
  { name: 'Aruba', code: 'aw' },
  { name: 'Åland Islands', code: 'ax' },
  { name: 'Azerbaijan', code: 'az' },
  { name: 'Bosnia and Herzegovina', code: 'ba' },
  { name: 'Barbados', code: 'bb' },
  { name: 'Bangladesh', code: 'bd' },
  { name: 'Belgium', code: 'be' },
  { name: 'Burkina Faso', code: 'bf' },
  { name: 'Bulgaria', code: 'bg' },
  { name: 'Bahrain', code: 'bh' },
  { name: 'Burundi', code: 'bi' },
  { name: 'Benin', code: 'bj' },
  { name: 'Saint Barthélemy', code: 'bl' },
  { name: 'Bermuda', code: 'bm' },
  { name: 'Brunei', code: 'bn' },
  { name: 'Bolivia', code: 'bo' },
  { name: 'Bonaire', code: 'bq-bo' },
  { name: 'Saba', code: 'bq-sa' },
  { name: 'Sint Eustatius', code: 'bq-se' },
  { name: 'Bonaire', code: 'bq' },
  { name: 'Brazil', code: 'br' },
  { name: 'Bahamas', code: 'bs' },
  { name: 'Bhutan', code: 'bt' },
  { name: 'Bouvet Island', code: 'bv' },
  { name: 'Botswana', code: 'bw' },
  { name: 'Belarus', code: 'by' },
  { name: 'Belize', code: 'bz' },
  { name: 'British Columbia', code: 'ca-bc' },
  { name: 'Canada', code: 'ca' },
  { name: 'Cocos Islands', code: 'cc' },
  { name: 'Congo, Democratic Republic of the', code: 'cd' },
  { name: 'Central African Republic', code: 'cf' },
  { name: 'Congo', code: 'cg' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'Grisons', code: 'ch-gr' },
  { name: 'Ivory Coast', code: 'ci' },
  { name: 'Cook Islands', code: 'ck' },
  { name: 'Chile', code: 'cl' },
  { name: 'Cameroon', code: 'cm' },
  { name: 'China', code: 'cn' },
  { name: 'Xinjiang', code: 'cn-xj' },
  { name: 'Colombia', code: 'co' },
  { name: 'Clipperton Island', code: 'cp' },
  { name: 'Island of Sark', code: 'cq' },
  { name: 'Costa Rica', code: 'cr' },
  { name: 'Cuba', code: 'cu' },
  { name: 'Cabo Verde', code: 'cv' },
  { name: 'Curaçao', code: 'cw' },
  { name: 'Christmas Island', code: 'cx' },
  { name: 'Cyprus', code: 'cy' },
  { name: 'Czechia', code: 'cz' },
  { name: 'Germany', code: 'de' },
  { name: 'Djibouti', code: 'dj' },
  { name: 'Denmark', code: 'dk' },
  { name: 'Dominica', code: 'dm' },
  { name: 'Diego Garcia', code: 'dg' },
  { name: 'Dominican Republic', code: 'do' },
  { name: 'Algeria', code: 'dz' },
  { name: 'Ceuta', code: 'ea' },
  { name: 'Earth', code: 'earth' },
  { name: 'East African Federation', code: 'east_african_federation' },
  { name: 'Easter Island', code: 'easter_island' },
  { name: 'Galápagos', code: 'ec-w' },
  { name: 'Ecuador', code: 'ec' },
  { name: 'Estonia', code: 'ee' },
  { name: 'Egypt', code: 'eg' },
  { name: 'Western Sahara', code: 'eh' },
  { name: 'Eritrea', code: 'er' },
  { name: 'Aragón', code: 'es-ar' },
  { name: 'Ceuta', code: 'es-ce' },
  { name: 'Canary Islands', code: 'es-cn' },
  { name: 'Catalonia', code: 'es-ct' },
  { name: 'Galicia', code: 'es-ga' },
  { name: 'Balearic Islands', code: 'es-ib' },
  { name: 'Melilla', code: 'es-ml' },
  { name: 'Basque Country', code: 'es-pv' },
  { name: 'Spain', code: 'es-variant' },
  { name: 'Spain', code: 'es' },
  { name: 'Ethiopia', code: 'et' },
  { name: 'Oromia', code: 'et-or' },
  { name: 'Tigrai', code: 'et-ti' },
  { name: 'European Union', code: 'eu' },
  { name: 'European Union', code: 'european_union' },
  { name: 'Ewe nation', code: 'ewe' },
  { name: 'Finland', code: 'fi' },
  { name: 'Fiji', code: 'fj' },
  { name: 'Falkland Islands', code: 'fk' },
  { name: 'Micronesia', code: 'fm' },
  { name: 'Faroe Islands', code: 'fo' },
  { name: 'France', code: 'fr' },
  { name: 'Bretagne', code: 'fr-bre' },
  { name: 'Clipperton Island', code: 'fr-cp' },
  { name: 'France', code: 'fx' },
  { name: 'Gabon', code: 'ga' },
  { name: 'Cornwall', code: 'gb-con' },
  { name: 'England', code: 'gb-eng' },
  { name: 'Northern Ireland', code: 'gb-nir' },
  { name: 'Orkney', code: 'gb-ork' },
  { name: 'Scotland', code: 'gb-sct' },
  { name: 'Wales', code: 'gb-wls' },
  { name: 'United Kingdom', code: 'gb' },
  { name: 'Grenada', code: 'gd' },
  { name: 'Abkhazia', code: 'ge-ab' },
  { name: 'Georgia', code: 'ge' },
  { name: 'French Guiana', code: 'gf' },
  { name: 'Guernsey', code: 'gg' },
  { name: 'Ghana', code: 'gh' },
  { name: 'Gibraltar', code: 'gi' },
  { name: 'Greenland', code: 'gl' },
  { name: 'Gambia', code: 'gm' },
  { name: 'Guinea', code: 'gn' },
  { name: 'Guadeloupe', code: 'gp' },
  { name: 'Equatorial Guinea', code: 'gq' },
  { name: 'Greece', code: 'gr' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'gs' },
  { name: 'Guatemala', code: 'gt' },
  { name: 'Guarani', code: 'guarani' },
  { name: 'Guam', code: 'gu' },
  { name: 'Guinea-Bissau', code: 'gw' },
  { name: 'Guyana', code: 'gy' },
  { name: 'Hausa', code: 'hausa' },
  { name: 'Hong Kong', code: 'hk' },
  { name: 'Hmong', code: 'hmong' },
  { name: 'Heard Island and McDonald Islands', code: 'hm' },
  { name: 'Honduras', code: 'hn' },
  { name: 'Croatia', code: 'hr' },
  { name: 'Haiti', code: 'ht' },
  { name: 'Hungary', code: 'hu' },
  { name: 'Canary Islands', code: 'ic' },
  { name: 'Indonesia', code: 'id' },
  { name: 'West Java', code: 'id-jb' },
  { name: 'Central Java', code: 'id-jt' },
  { name: 'Ireland', code: 'ie' },
  { name: 'Israel', code: 'il' },
  { name: 'Isle of Man', code: 'im' },
  { name: 'India', code: 'in' },
  { name: 'Assam', code: 'in-as' },
  { name: 'Gujarat', code: 'in-gj' },
  { name: 'Karnātaka', code: 'in-ka' },
  { name: 'Odisha', code: 'in-or' },
  { name: 'Tamil Nadu', code: 'in-tn' },
  { name: 'British Indian Ocean Territory', code: 'io' },
  { name: 'Iraq', code: 'iq' },
  { name: 'Iran', code: 'ir' },
  { name: 'Iceland', code: 'is' },
  { name: 'Aosta', code: 'it-23' },
  { name: 'Sicily', code: 'it-82' },
  { name: 'Sardinia', code: 'it-88' },
  { name: 'Italy', code: 'it' },
  { name: 'Jersey', code: 'je' },
  { name: 'Jamaica', code: 'jm' },
  { name: 'Jordan', code: 'jo' },
  { name: 'Japan', code: 'jp' },
  { name: 'Kanuri', code: 'kanuri' },
  { name: 'Kenya', code: 'ke' },
  { name: 'Kyrgyzstan', code: 'kg' },
  { name: 'Cambodia', code: 'kh' },
  { name: 'Kiribati', code: 'ki' },
  { name: 'Kikuyu', code: 'kikuyu' },
  { name: 'Comoros', code: 'km' },
  { name: 'Saint Kitts and Nevis', code: 'kn' },
  { name: 'Kongo', code: 'kongo' },
  { name: 'North Korea', code: 'kp' },
  { name: 'South Korea', code: 'kr' },
  { name: 'Kurdistan', code: 'kurdistan' },
  { name: 'Kuwait', code: 'kw' },
  { name: 'Cayman Islands', code: 'ky' },
  { name: 'Kazakhstan', code: 'kz' },
  { name: 'Laos', code: 'la' },
  { name: 'Lebanon', code: 'lb' },
  { name: 'Saint Lucia', code: 'lc' },
  { name: 'Liechtenstein', code: 'li' },
  { name: 'Sri Lanka', code: 'lk' },
  { name: 'Liberia', code: 'lr' },
  { name: 'Lesotho', code: 'ls' },
  { name: 'Lithuania', code: 'lt' },
  { name: 'Luxembourg', code: 'lu' },
  { name: 'Latvia', code: 'lv' },
  { name: 'Libya', code: 'ly' },
  { name: 'Morocco', code: 'ma' },
  { name: 'Malayali', code: 'malayali' },
  { name: 'Manipur', code: 'manipur' },
  { name: 'Maori', code: 'maori' },
  { name: 'Monaco', code: 'mc' },
  { name: 'Moldova', code: 'md' },
  { name: 'Montenegro', code: 'me' },
  { name: 'Saint-Martin', code: 'mf' },
  { name: 'Madagascar', code: 'mg' },
  { name: 'Marshall Islands', code: 'mh' },
  { name: 'Mizoram', code: 'mizoram' },
  { name: 'North Macedonia', code: 'mk' },
  { name: 'Mali', code: 'ml' },
  { name: 'Myanmar', code: 'mm' },
  { name: 'Mongolia', code: 'mn' },
  { name: 'Macao', code: 'mo' },
  { name: 'Northern Mariana Islands', code: 'mp' },
  { name: 'Martinique', code: 'mq' },
  { name: 'Mauritania', code: 'mr' },
  { name: 'Montserrat', code: 'ms' },
  { name: 'Malta', code: 'mt' },
  { name: 'Mauritius', code: 'mu' },
  { name: 'MalItemes', code: 'mv' },
  { name: 'Malawi', code: 'mw' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Malaysia', code: 'my' },
  { name: 'Mozambique', code: 'mz' },
  { name: 'Namibia', code: 'na' },
  { name: 'New Caledonia', code: 'nc' },
  { name: 'NATO', code: 'nato' },
  { name: 'Niger', code: 'ne' },
  { name: 'Norfolk Island', code: 'nf' },
  { name: 'Nigeria', code: 'ng' },
  { name: 'Nicaragua', code: 'ni' },
  { name: 'Netherlands', code: 'nl' },
  { name: 'Friesland', code: 'nl-fr' },
  { name: 'Norway', code: 'no' },
  { name: 'Northern Cyprus', code: 'northern_cyprus' },
  { name: 'Nepal', code: 'np' },
  { name: 'Nauru', code: 'nr' },
  { name: 'Niue', code: 'nu' },
  { name: 'New Zealand', code: 'nz' },
  { name: 'Occitania', code: 'occitania' },
  { name: 'Olympics', code: 'olympics' },
  { name: 'Oman', code: 'om' },
  { name: 'Otomi', code: 'otomi' },
  { name: 'Panama', code: 'pa' },
  { name: 'Peru', code: 'pe' },
  { name: 'French Polynesia', code: 'pf' },
  { name: 'Papua New Guinea', code: 'pg' },
  { name: 'Philippines', code: 'ph' },
  { name: 'Pakistan', code: 'pk' },
  { name: 'Kashmīr', code: 'pk-jk' },
  { name: 'Sindh', code: 'pk-sd' },
  { name: 'Poland', code: 'pl' },
  { name: 'Saint Pierre and Miquelon', code: 'pm' },
  { name: 'Pitcairn Islands', code: 'pn' },
  { name: 'Puerto Rico', code: 'pr' },
  { name: 'Palestine', code: 'ps' },
  { name: 'Azores', code: 'pt-20' },
  { name: 'Madeira', code: 'pt-30' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Palau', code: 'pw' },
  { name: 'Paraguay', code: 'py' },
  { name: 'Qatar', code: 'qa' },
  { name: 'Quechua', code: 'quechua' },
  { name: 'Réunion', code: 're' },
  { name: 'Romania', code: 'ro' },
  { name: 'Serbia', code: 'rs' },
  { name: 'Russia', code: 'ru' },
  { name: 'Bashkortostan, Respublika', code: 'ru-ba' },
  { name: 'Chechenskaya Respublika', code: 'ru-ce' },
  { name: 'Chuvashskaya Respublika', code: 'ru-cu' },
  { name: 'Dagestan, Respublika', code: 'ru-da' },
  { name: 'Komi, Respublika', code: 'ru-ko' },
  { name: 'Tatarstan', code: 'ru-ta' },
  { name: 'Udmurtskaya Respublika', code: 'ru-ud' },
  { name: 'Rwanda', code: 'rw' },
  { name: 'Saudi Arabia', code: 'sa' },
  { name: 'Sami', code: 'sami' },
  { name: 'Solomon Islands', code: 'sb' },
  { name: 'Seychelles', code: 'sc' },
  { name: 'Sudan', code: 'sd' },
  { name: 'Sweden', code: 'se' },
  { name: 'Singapore', code: 'sg' },
  { name: 'Saint Helena', code: 'sh' },
  { name: 'Saint Helena', code: 'sh-hl' },
  { name: 'Ascension Island', code: 'sh-ac' },
  { name: 'Tristan da Cunha', code: 'sh-ta' },
  { name: 'Slovenia', code: 'si' },
  { name: 'Svalbard and Jan Mayen', code: 'sj' },
  { name: 'Slovakia', code: 'sk' },
  { name: 'Sierra Leone', code: 'sl' },
  { name: 'San Marino', code: 'sm' },
  { name: 'Senegal', code: 'sn' },
  { name: 'Somalia', code: 'so' },
  { name: 'Somaliland', code: 'somaliland' },
  { name: 'South Ossetia', code: 'south_ossetia' },
  { name: 'Soviet Union', code: 'soviet_union' },
  { name: 'Suriname', code: 'sr' },
  { name: 'South Sudan', code: 'ss' },
  { name: 'São Tomé and Príncipe', code: 'st' },
  { name: 'Soviet Union', code: 'su' },
  { name: 'El Salvador', code: 'sv' },
  { name: 'Sint Maarten', code: 'sx' },
  { name: 'Syria', code: 'sy' },
  { name: 'Eswatini', code: 'sz' },
  { name: 'Tristan da Cunha', code: 'ta' },
  { name: 'Turks and Caicos Islands', code: 'tc' },
  { name: 'Chad', code: 'td' },
  { name: 'French Southern Territories', code: 'tf' },
  { name: 'Togo', code: 'tg' },
  { name: 'Thailand', code: 'th' },
  { name: 'Tibet', code: 'tibet' },
  { name: 'Tajikistan', code: 'tj' },
  { name: 'Tokelau', code: 'tk' },
  { name: 'Timor-Leste', code: 'tl' },
  { name: 'Turkmenistan', code: 'tm' },
  { name: 'Tunisia', code: 'tn' },
  { name: 'Tonga', code: 'to' },
  { name: 'Torres Strait Islands', code: 'torres_strait_islands' },
  { name: 'Turkey', code: 'tr' },
  { name: 'Transnistria', code: 'transnistria' },
  { name: 'Trinidad and Tobago', code: 'tt' },
  { name: 'Tuvalu', code: 'tv' },
  { name: 'Taiwan', code: 'tw' },
  { name: 'Tanzania', code: 'tz' },
  { name: 'Ukraine', code: 'ua' },
  { name: 'Uganda', code: 'ug' },
  { name: 'United Kingdom', code: 'uk' },
  { name: 'United Nations', code: 'united_nations' },
  { name: 'U.S. Minor Outlying Islands', code: 'um' },
  { name: 'Hawaii', code: 'us-hi' },
  { name: 'United Nations', code: 'un' },
  { name: 'United States of America', code: 'us' },
  { name: 'Uruguay', code: 'uy' },
  { name: 'Uzbekistan', code: 'uz' },
  { name: 'Holy See', code: 'va' },
  { name: 'Saint Vincent and the Grenadines', code: 'vc' },
  { name: 'Venezuela', code: 've' },
  { name: 'Virgin Islands', code: 'vg' },
  { name: 'Virgin Islands', code: 'vi' },
  { name: 'Vietnam', code: 'vn' },
  { name: 'Vanuatu', code: 'vu' },
  { name: 'Wallis and Futuna', code: 'wf' },
  { name: 'Wiphala', code: 'wiphala' },
  { name: 'Samoa', code: 'ws' },
  { name: 'Kosovo', code: 'xk' },
  { name: 'Yemen', code: 'ye' },
  { name: 'Mayotte', code: 'yt' },
  { name: 'Yorubaland', code: 'yorubaland' },
  { name: 'South Africa', code: 'za' },
  { name: 'Zambia', code: 'zm' },
  { name: 'Zimbabwe', code: 'zw' },
];
